spring:
  application:
    name: Doc-Vault
  datasource:
    url: jdbc:postgresql://localhost:5432/doc-vault
    username: postgres
    password: Dhanesh
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    cors:
      allowed-origins: http://localhost:3000
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

server.port: 9090

aws:
  s3:
    bucketName: doc-vault
  accessKeyId:
  secretAccessKey:
springdoc:
  api-docs:
    path: /api-docs


